; Saboteur II: 48K Mod by TheAlfest — Combined Assembly
; Generated by split_mod.py for reassembly verification
;
; Reassemble with:
;   pasmo --bin _mod_combined.asm mod_reassembled.bin

	org	0620ch

	INCLUDE "entry_jump.asm"
	INCLUDE "data_text.asm"
	INCLUDE "data_rooms.asm"
	INCLUDE "data_tables1.asm"
	INCLUDE "code_entry.asm"
	INCLUDE "data_highscores.asm"
	INCLUDE "data_infoscreen.asm"
	INCLUDE "code_infoscreen.asm"
	INCLUDE "code_newgame.asm"
	INCLUDE "data_tables2.asm"
	INCLUDE "data_entities.asm"
	INCLUDE "data_sprites.asm"
	INCLUDE "code_input.asm"
	INCLUDE "code_engine.asm"
	INCLUDE "data_buffer.asm"
	INCLUDE "data_gfx.asm"
	INCLUDE "data_newtables.asm"
	INCLUDE "code_isr.asm"

